### ISSUE TITLE
Отключение функции показа фракции при наведении на маркер

### ISSUE THREAD

**Issue by Chief01** [sweetSTEAM/swt_markers_a3#1]
Добрый день. 
Давно используем ваш мод на Red Bear Community. Все работает отлично, но функция показа фракции при наведении на маркер игроков стороны лишняя на твт играх. Игроки используют данную функцию чтобы узнавать жив или мертв игрок во время боя. Прошу помочь с отключением данной функции. Если нет времени то хотя бы подскажите как это можно сделать.

**Comment by sweetSTEAM** [comment]
Привет!
В логах (в брифинге) эту фичу с подсветкой ников тоже выключить?

**Comment by sweetSTEAM** [comment]
Diff вот такой https://github.com/sweetSTEAM/swt_markers_a3/commit/50f3a4f9c0f08a515ef26a683249b6f8ef8638cc
Вам так удобно или помочь запаковать в pbo?

**Comment by Chief01** [comment]
Если в PBO упакуешь будет вообще здорово! 17.06.2018, 01:08, "Vasiliy Vdovkin" <notifications@github.com>:Diff вот такой 50f3a4f
Вам так удобно или помочь запаковать в pbo?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


-- С уважением, Алексей Смоленков,Руководитель проектно - сметного отдела ООО "НОВОКАМ-СЕРВИС"р.Татарстан, г. Набережные ЧелныМосковский проспект д.140тел. (8552) 59-77-19/ 59-20-65icq: 662081505

**Comment by Chief01** [comment]
Да везде эту фишку бы отключить, она не нужна. Если запакуете то будем очень благодарны!

**Comment by Chief01** [comment]
Там принадлежность к фракции показываются синий зеленый или красный а если белый то мертв.

**Comment by sweetSTEAM** [comment]
Да это плохо было реализовано совсем.
А какая у вас pbo сейчас?

**Comment by Chief01** [comment]
версию 2.1 юзаем https://yadi.sk/d/-IyaowrA3Xzemc

**Comment by sweetSTEAM** [comment]
https://www.dropbox.com/s/19dw02mdmadx08t/swt_markers_a3.pbo?dl=1

**Comment by Chief01** [comment]
В этой версии подсветка отключена?

**Comment by sweetSTEAM** [comment]
Да

**Comment by Chief01** [comment]
Большое спасибо! 
Ещё вопрос по теме маркеров. Мы хотим организовать чтобы маркеры в синий канал могли ставить только те кто обладает ДВ рациями не знаешь, как это организовать?

**Comment by sweetSTEAM** [comment]
Сделать здесь (https://github.com/sweetSTEAM/swt_markers_a3/blob/7e79c727bacea469e51e34d4f41b5d4b7b46bea6/Logic/sendMark.sqf#L4) такую же проверку только не на переменную, а на то, что у плеера есть бекпак определённого класса (дв) https://community.bistudio.com/wiki/backpack

**Comment by Chief01** [comment]
Спасибо огромное!
